job-compile:
  stage: compile
  script:
    - mvn compile

job-test:
  stage: test
  script:
    - mvn test

deploy-prod:
  stage: deploy
  script:
    - mvn package
    - export PORT=5000
    - sh target/bin/simplewebapp
