stages:
  - build
  - test
  - deploy
  - tsuru

build:
  stage: build
  script:
    - mvn compile

test:
  stage: test
  script:
    - mvn test

deploy:
  stage: deploy
  script:
    - export PORT=5000

tsuru:
  stage: tsuru
  script:
    - mvn package
    - tsuru app deploy --app simplewebapp-tc2323 --dockerfile .