stages:
  - compile
  - test
  - deploy
  - tsuru

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

cache:
  paths:
    - .m2/repository


compile:
  stage: compile
  script:
    - mvn compile

test:
  stage: test
  script:
    - mvn test

deploy:
  stage: deploy
  script:
    - mvn package

tsuru:
  stage: tsuru
  script:
    - tsuru app deploy --app simplewebapp-tc2323 --dockerfile .