stages:
  - compile
  - test
  - build
  - deploy
  - tsuru

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"
  DOCKER_DRIVER: overlay2

cache:
  paths:
    - .m2/repository


compile:
  stage: compile
  script:
    - echo "Compiling..."
    - mvn compile
    - echo "Compiled successfully"

test:
  stage: test
  script:
    - echo "Testing..."
    - mvn test
    - echo "Tests ran successfully"

build_image:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  script:
    - echo "Building Docker image..."
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" 
      "$CI_REGISTRY"
    - docker build --pull -t "$CI_REGISTRY_IMAGE:$CI_COMMIT_SHA" .
    - docker push "$CI_REGISTRY_IMAGE:$CI_COMMIT_SHA"


deploy:
  stage: deploy
  script:
    - echo "Packaging application..."
    - mvn package
    - echo "Packaged successfully"

tsuru:
  stage: tsuru
  script:
    - echo "Deploying with Tsuru..."
    - tsuru app deploy --app simplewebapp-tc2323 
      --image "$CI_REGISTRY_IMAGE:$CI_COMMIT_SHA" 
    - echo "Deployed successfully"