stages:
  - build
  - test
  - deploy

build:
  stage: build
  script:
    - mvn compile

test:
  stage: test
  script:
    - mvn test

deploy:
  stage: deploy
  script:
    - mvn package
    - export PORT=5000
    - sudo ufw allow 5000
    - sh target/bin/simplewebapp
