stages:
  - compile
  - test
  - deploy
  - tsuru

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

cache:
  paths:
    - .m2/repository


compile:
  stage: compile
  script:
    - echo "Compiling..."
    - mvn compile
    - echo "Compiled successfully"

test:
  stage: test
  script:
    - echo "Testing..."
    - mvn test
    - echo "Tests ran successfully"

deploy:
  stage: deploy
  script:
    - echo "Packaging and deploying application..."
    - mvn package
    - export PORT=5000
    - nohup sh target/bin/simplewebapp &
    - echo "Packaged successfully"

tsuru:
  stage: tsuru
  script:
    - echo "Deploying with Tsuru..."
    - tsuru app deploy --app simplewebapp-tc2323 --dockerfile .
    - echo "Deployed successfully"