name: Java CI Workflow

# Define the trigger for the workflow
on:
  push:
    branches:
      - master
      - feat--container-registry
  pull_request:
    branches:
      - master  

jobs:
  compile:
    runs-on: ubuntu-latest  # Use the latest Ubuntu environment
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adoptopenjdk'  


      - name: Cache Maven dependencies
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Compile
        run: mvn compile

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'

      - name: Run tests
        run: mvn test

  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'

      - name: Build and package application
        run: mvn package

      - name: Deploy the application
        run: |
          export PORT=5000
          nohup sh target/bin/simplewebapp > simplewebapp.log 2>&1 </dev/null &

  tsuru:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Deploy with Tsuru
        run: |
          echo "Deploying with Tsuru..."
          tsuru app deploy --app simplewebapp-tc2323 --dockerfile .
          echo "Deployed successfully"
